Updates

diff --git a/scripts/simg_files_to_working_folder b/scripts/simg_files_to_working_folder
--- a/scripts/simg_files_to_working_folder
+++ b/scripts/simg_files_to_working_folder
@@ -1,6 +1,6 @@
 ############################################################################
 #
-# Copyright (c) 2010-2011 dsixda - dislam@rocketmail.com
+# Copyright (c) 2011 - dsixda (dislam@rocketmail.com)
 #
 # Android Kitchen is 100% free.  This script file is intended for personal
 # and/or educational use only.  It may not be duplicated for monetary
@@ -33,10 +33,7 @@ then
   then
     mv $build_dir/cache.img $build_dir/system
   else
-    echo
-    echo "Warning: No cache.img found.  You can unpack a cache.img separately"
-    echo "by running the plugin script in the kitchen's Advanced menu options."
-    echo
+    scripts/show_cache_warning cache.img 
   fi
 
   # Sometimes images have zero permissions set when extracted from TAR archive,
@@ -56,11 +53,7 @@ else
     then
       echo "Found original_update/cache.img"
     else
-      echo
-      echo "Warning: original_update/cache.img Not found.  You can unpack a"
-      echo "cache.img separately by running the plugin script in the kitchen's"
-      echo "Advanced menu."
-      echo
+      scripts/show_cache_warning original_update/cache.img
     fi
   else
 
@@ -111,33 +104,11 @@ echo
 # Compile sigm2img
 #
 
-simg2img_file=simg2img
-if [ `uname | grep CYGWIN` ]
+scripts/compile_simg2img
+if [ "$?" == "1" ]
 then
-  simg2img_file=$simg2img_file.exe
+  exit 1
 fi
-
-if [ -e tools/samsung_files/simg2img_files/$simg2img_file ]
-then
-  echo "Found $simg2img_file"
-else
-  echo "Compiling simg2img ..."
-
-  cd tools/samsung_files/simg2img_files
-  gcc -c sparse_crc32.c
-  gcc sparse_crc32.o simg2img.c -w -o simg2img
-  rm *.o 
-  cd ../../..
-
-  if [ -e tools/samsung_files/simg2img_files/$simg2img_file ]
-  then
-    echo "$simg2img_file successfully compiled"
-  else
-    echo "Error: $simg2img_file not successfully compiled!"
-    exit 1
-  fi    
-fi
-
 
 
 
@@ -161,13 +132,13 @@ cd ../..
 #
 
 echo
-echo "Unpacking factoryfs.img into ext4 format ..."
+echo "Converting factoryfs.img into a format for unpacking ..."
 tools/samsung_files/simg2img_files/simg2img $src_dir/factoryfs.img \
   $system_dir/ext4_factoryfs.img
 
 if [ ! -e $system_dir/ext4_factoryfs.img ]
 then
-  echo "Unable to unpack factoryfs.img!"
+  echo "Unable to convert factoryfs.img!"
   exit 1
 fi
 
@@ -264,13 +235,13 @@ then
     #
     # Convert cache.img to ext4
     #
-    echo "Unpacking cache.img into ext4 format ..."
+    echo "Converting cache.img into a format for unpacking ..."
     tools/samsung_files/simg2img_files/simg2img $src_dir/cache.img \
       $system_dir/ext4_cache.img
 
     if [ ! -e $system_dir/ext4_cache.img ]
     then
-      echo "Unable to unpack cache.img!"
+      echo "Unable to convert cache.img!"
       exit 1
     fi
 
@@ -297,49 +268,8 @@ then
       echo
     fi
 
-    if [ ! -e sec_csc.zip ]
-    then
-      echo "WARNING: sec_csc.zip not found!"
-    else
-      echo "Extracting the required files from sec_csc.zip ..."
-      unzip -q sec_csc.zip -d temp_csc
-
-      # 
-      # Carrier bloatware
-      #
-
-      if [ -d temp_csc/system/app ]
-      then
-        echo
-        echo "These are apps found in sec_csc.zip:"
-        ls temp_csc/system/app
-        echo
-        echo -n "Copy the apps to your working folder (y/n)? (default: n): "
-
-        read do_copy
-        echo
-
-        if [ "$do_copy" != "y" ]
-        then
-          rm -vrf temp_csc/system/app
-        fi
-      fi
-
-      rm -rf temp_csc/META-INF
-      mv temp_csc/system/* .
-      rm -rf temp_csc
-    fi
-
-    rm -f sec_csc.zip 2>/dev/null
-    if [ "$?" == "1" ]
-    then
-      echo
-      echo "WARNING: sec_csc.zip is in use.  Remove file manually."
-      echo
-    fi
-
     cd ../..
-
+    scripts/unzip_csc $build_dir
   fi
 fi
 
diff --git a/scripts/tar_file_to_working_folder b/scripts/tar_file_to_working_folder
--- a/scripts/tar_file_to_working_folder
+++ b/scripts/tar_file_to_working_folder
@@ -1,6 +1,6 @@
 ############################################################################
 #
-# Copyright (c) 2010-2011 dsixda - dislam@rocketmail.com
+# Copyright (c) 2011 - dsixda (dislam@rocketmail.com)
 #
 # Android Kitchen is 100% free.  This script file is intended for personal
 # and/or educational use only.  It may not be duplicated for monetary
@@ -47,7 +47,9 @@ mkdir $build_dir
 echo
 echo "Extracting ROM ..."
 
-tar xvf original_update/$update_file -C $build_dir -x factoryfs.img cache.img modem.bin zImage factoryfs.rfs cache.rfs PDA.tar.md5 CSC.tar.md5 PHONE.tar.md5 PDA.tar CSC.tar PHONE.tar 2>/dev/null
+tar xvf original_update/$update_file -C $build_dir -x factoryfs.img cache.img modem.bin \
+      zImage factoryfs.rfs cache.rfs PDA.tar.md5 CSC.tar.md5 PHONE.tar.md5 PDA.tar CSC.tar \
+      PHONE.tar system.img.ext4 cache.img.ext4 boot.img system 2>/dev/null
 
 cd $build_dir
 
@@ -65,6 +67,18 @@ then
 
   cd ..
   scripts/simg_files_to_working_folder no_create $2
+  exit $?
+
+elif [ -e system.img.ext4 ]
+then
+
+  if [ -e boot.img ]
+  then
+    echo "Found boot.img"
+  fi
+
+  cd ..
+  scripts/simg_ext4_files_to_working_folder no_create $2
   exit $?
 
 elif [ -e factoryfs.rfs ]
@@ -95,8 +109,31 @@ then
   scripts/sgs_tarmd5_files_to_working_folder no_create $2
   exit $?
 
+
+elif [ -d system ]
+then
+
+  mkdir -p META-INF/com/google/android
+  echo
+  echo "Adding an update-script ..."
+  cp ../tools/update_files/update-script META-INF/com/google/android/
+
+  cd ..
+  if [ "$2" != "kernel_only" ] && [ "$2" != "name_given" ]
+  then
+
+    scripts/fix_update_script 
+
+    # Modify the update-script with features found
+    scripts/fix_update_script_with_features
+    
+    scripts/remove_recovery
+  fi
+    
+  exit 0
+
 else
-  echo "Error: No image files found in TAR archive!"
+  echo "Error: No image files identified in TAR archive!"
   echo 
   cd ..
   exit 1
